# Joining and Splitting Arrays (Combining and Breaking Data)

In real projects, you rarely work with just one source of data. You might have sensor data from Room A and sensor data from Room B, and you want to **glue them together** into one big matrix.
*   In regular programming (like TypeScript), combining arrays is done via `.concat()` or the spread operator `[...arr1, ...arr2]`.
*   In NumPy, we have to deal with **multi-dimensional dimensions (axes)**. We can stack arrays **vertically** (adding new rows) or **horizontally** (adding new columns).
*   Similarly, we can **split** a single array into multiple smaller chunks (for example, splitting a dataset into $80\%$ for training a machine learning model and $20\%$ for testing it).

### Simple Explanation with an Everyday Analogy
Imagine you are building a wall with **Lego blocks**:
*   **Vertical Stacking (`vstack`)**: Placing one block **directly on top** of another block. This increases the height (adds rows).
*   **Horizontal Stacking (`hstack`)**: Placing one block **side-by-side** with another block. This increases the width (adds columns).
*   **Splitting**: Taking a long Lego block and **snapping it in half** to create two separate smaller blocks.


#### Stacking Vertically and Horizontally: `vstack()` and `hstack()`
For beginners, `vstack` (vertical stack) and `hstack` (horizontal stack) are the easiest and safest ways to combine arrays.

In [2]:
import numpy as np

# Create two 1D arrays
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

# Stack vertically (on top of each other)
# Note: You MUST pass them as a tuple: (v1, v2) with double parenthesis!
v_stack = np.vstack((v1, v2))
print("Vertically stacked (becomes a 2D grid):\n", v_stack)

# Stack horizontally (side-by-side)
h_stack = np.hstack((v1, v2))
print("\nHorizontally stacked (remains a 1D line):", h_stack)

Vertically stacked (becomes a 2D grid):
 [[1 2 3]
 [4 5 6]]

Horizontally stacked (remains a 1D line): [1 2 3 4 5 6]


#### Concatenating along Axes: `concatenate()`
`np.concatenate()` is the general-purpose function for merging arrays. You must specify the `axis` parameter:
*   `axis=0`: Merges arrays row-wise (vertically).
*   `axis=1`: Merges arrays column-wise (horizontally).


In [3]:
import numpy as np

m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])

# axis=0: Concatenate row-wise (vertical)
res_axis0 = np.concatenate((m1, m2), axis=0)
print("Concatenate axis=0:\n", res_axis0)

# axis=1: Concatenate column-wise (horizontal)
res_axis1 = np.concatenate((m1, m2), axis=1)
print("\nConcatenate axis=1:\n", res_axis1)

Concatenate axis=0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Concatenate axis=1:
 [[1 2 5 6]
 [3 4 7 8]]


#### Adding a New Layer/Dimension: `stack()`
While `concatenate` merges on existing dimensions, `np.stack()` stacks them along a **brand new dimension**. Think of it as placing two identical pictures on top of each other to create a 3D book.


In [4]:
import numpy as np

s1 = np.array([1, 2, 3])
s2 = np.array([4, 5, 6])

# Stacking creates a 3D depth layer!
stacked = np.stack((s1, s2))
print("Stacked shape:", stacked.shape)
print("Stacked array:\n", stacked)

Stacked shape: (2, 3)
Stacked array:
 [[1 2 3]
 [4 5 6]]


#### Splitting Arrays: `split()`
The `np.split()` function splits an array into multiple sub-arrays. You must pass:
1.  The array you want to split.
2.  The number of equal splits you want (an integer), or a list of indices where the splits should happen.
3.  The `axis` along which to split (defaults to `axis=0`).

In [5]:
import numpy as np

grid = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90],
    [100, 110, 120]
])

# Split vertically (axis=0) into 2 equal parts
parts = np.split(grid, 2, axis=0)
print("Part 1:\n", parts[0])
print("\nPart 2:\n", parts[1])

Part 1:
 [[10 20 30]
 [40 50 60]]

Part 2:
 [[ 70  80  90]
 [100 110 120]]


### Common Mistakes Beginners Make
1.  **Forgetting the double parenthesis**: Writing `np.vstack(v1, v2)` instead of `np.vstack((v1, v2))`. NumPy expects a single sequence argument, so you must wrap the arrays in a tuple!
2.  **Incompatible sizes for concatenation**: Trying to use `vstack` on arrays that have different number of columns. To stack vertically, the **number of columns must match exactly**.
3.  **Unequal splits**: If you try to split a 5-row array into 2 parts using `np.split(arr, 2)`, NumPy will throw an error because 5 cannot be divided into 2 equal-sized arrays.


#### Exercise 1
Create two 1D arrays: `a = [10, 20]` and `b = [30, 40]`.
1. Use `np.hstack` to join them into a flat 1D array.
2. Use `np.vstack` to join them into a 2D matrix.

In [6]:
import numpy as np
a = np.array([10, 20])
b = np.array([30, 40])

h = np.hstack((a, b))
v = np.vstack((a, b))

print("Horizontal:", h)
print("Vertical:\n", v)

Horizontal: [10 20 30 40]
Vertical:
 [[10 20]
 [30 40]]


*Explanation*: `hstack` glues elements side-by-side. `vstack` stacks them on top of each other, turning two 1D vectors of shape `(2,)` into a single 2D matrix of shape `(2, 2)`.


#### Exercise 2
Given these two 2D matrices:
```python
x = np.array([[1, 2], [3, 4]])
y = np.array([[5], [6]])
```
Merge them together so you get a single 2x3 matrix:
```text
[[1, 2, 5],
 [3, 4, 6]]
```
Which function and which axis should you use?

In [7]:
import numpy as np
x = np.array([[1, 2], [3, 4]])
y = np.array([[5], [6]])

# We want to add column-wise, so we use axis=1
merged = np.concatenate((x, y), axis=1)
print(merged)

[[1 2 5]
 [3 4 6]]


*Explanation*: Matrix `x` has shape `(2, 2)` (2 rows, 2 columns) and matrix `y` has shape `(2, 1)` (2 rows, 1 column). Since the number of rows matches, we can concatenate them horizontally along `axis=1`.



#### Exercise 3
You have a 6x3 matrix containing numbers from 1 to 18:
```python
data = np.arange(1, 19).reshape(6, 3)
```
1. Split this matrix vertically (axis 0) into 3 equal-sized matrices.
2. Take the first split result, and split it horizontally (axis 1) into 3 individual columns. Print the final columns.



In [8]:
import numpy as np
data = np.arange(1, 19).reshape(6, 3)

# 1. Split vertically into 3 equal parts
v_splits = np.split(data, 3, axis=0)

# 2. Split the first part horizontally into 3 columns
h_splits = np.split(v_splits[0], 3, axis=1)

print("First v_split:\n", v_splits[0])
print("\nColumn 1:\n", h_splits[0])
print("Column 2:\n", h_splits[1])
print("Column 3:\n", h_splits[2])

First v_split:
 [[1 2 3]
 [4 5 6]]

Column 1:
 [[1]
 [4]]
Column 2:
 [[2]
 [5]]
Column 3:
 [[3]
 [6]]


*Explanation*:
1. Splitting a 6x3 matrix vertically into 3 parts results in three 2x3 matrices (each with 2 rows and 3 columns).
2. Splitting a 2x3 matrix horizontally (axis 1) into 3 parts splits along columns, resulting in three 2x1 vectors (each representing one full column).
