# Saving and Loading Data (Keeping Your Work Safe)

When you train a machine learning model or process a massive dataset, you cannot keep your Python script running forever. You need a way to **save your arrays to your hard drive** and load them back later.
*   In regular web development, you might store objects in LocalStorage or save them as JSON text files.
*   In NumPy, saving massive arrays as text (like JSON or plain CSV) can be slow and use too much disk space.
*   NumPy provides highly optimized, **binary formats** (`.npy`) that compress data and load it almost instantly.
*   However, if you want your data to be readable by other software (like Microsoft Excel, R, or TypeScript), NumPy also lets you save arrays as plain text **CSV** files.

### Simple Explanation with an Everyday Analogy
Imagine you are building a complex jigsaw puzzle:
*   **Binary Save (`.npy`)**: You take the finished puzzle, place it gently in a special custom box, and close the lid. It fits perfectly and you can take it out and play instantly (super fast, fits perfectly).
*   **CSV/Text Save (`.csv`)**: You take a piece of paper and write down the coordinates and color of every single puzzle piece ("Piece 1 is red at (0,0)", "Piece 2 is blue..."). It is easy for anyone to read, but rebuilding the puzzle from those written notes takes a lot longer!



#### Saving and Loading NumPy Binary Files (`.npy`)
NumPy's proprietary binary format uses the `.npy` extension. It preserves all shape and data type information.

In [1]:
import numpy as np

my_array = np.array([[10, 20, 30], [40, 50, 60]])

# Save the array as a binary file
np.save("my_matrix.npy", my_array)
print("Array saved successfully!")

# Load the array back into memory
loaded_array = np.load("my_matrix.npy")
print("Loaded array:\n", loaded_array)

Array saved successfully!
Loaded array:
 [[10 20 30]
 [40 50 60]]


#### Saving and Loading Plain Text CSV Files (`.csv` or `.txt`)
If you want to view your data in a text editor or import it into Microsoft Excel, you can use `np.savetxt()` and `np.loadtxt()`.


In [2]:
import numpy as np

data = np.array([
    [1.5, 2.5],
    [3.5, 4.5]
])

# Save as plain text CSV (delimiter is a comma)
np.savetxt("my_data.csv", data, delimiter=",")
print("CSV saved successfully!")

# Load from CSV (you MUST specify the delimiter!)
loaded_data = np.loadtxt("my_data.csv", delimiter=",")
print("Loaded CSV data:\n", loaded_data)

CSV saved successfully!
Loaded CSV data:
 [[1.5 2.5]
 [3.5 4.5]]


### Common Mistakes Beginners Make
1.  **Forgetting the delimiter**: Saving a file with `delimiter=","` but trying to load it with `np.loadtxt("file.csv")` without specifying the delimiter. NumPy will fail to parse it because the default delimiter is a whitespace space.
2.  **Mixing binary and text functions**: Trying to load a binary `.npy` file using `np.loadtxt()` or a `.csv` file using `np.load()`.
3.  **Wasting space on huge datasets**: Saving massive millions-of-rows datasets as text CSV instead of `.npy`. This makes files 5x to 10x larger and loads much slower.


#### Exercise 1
Create a 1D array of odd numbers from 1 to 9. Save it to a file named `odds.npy`, then delete your original array variable using the `del` keyword, and load it back from the file.


In [3]:
import numpy as np

# Create array
odds = np.array([1, 3, 5, 7, 9])

# Save as binary
np.save("odds.npy", odds)

# Delete variable to simulate starting a new script
del odds

# Load back
loaded_odds = np.load("odds.npy")
print("Loaded odds:", loaded_odds)

Loaded odds: [1 3 5 7 9]


*Explanation*: `np.save` writes a binary block of memory directly to disk. When we call `np.load`, it reconstructs the array in memory exactly as it was.


#### Exercise 2 (Medium)
Create a 2D matrix of shape `(3, 3)` with random integers between 1 and 50. Save this matrix as a CSV file named `random_scores.csv` with a comma delimiter. Load it back and show the loaded array.


In [4]:
import numpy as np

# Set up generator and create random matrix
rng = np.random.default_rng(seed=42)
scores = rng.integers(1, 51, size=(3, 3))

# Save as CSV
np.savetxt("random_scores.csv", scores, delimiter=",")

# Load back
loaded_scores = np.loadtxt("random_scores.csv", delimiter=",")
print("Loaded scores:\n", loaded_scores)

Loaded scores:
 [[ 5. 39. 33.]
 [22. 22. 43.]
 [ 5. 35. 11.]]


*Explanation*: Since we saved using a comma `,` as the delimiter, we must tell `np.loadtxt` to expect commas by setting `delimiter=","`. Notice that `loadtxt` reads numbers as floating-point floats by default.
