# Fancy Indexing (Selecting Custom Elements)

We learned about standard indexing (`a[0]`) and slicing (`a[1:4]`). Slicing is great when you want to extract a continuous block of data or step through elements in a regular pattern.
However, in real-world datasets, the values you want are often scattered around randomly.

**Fancy Indexing** is the ability to pass a list or an array of indices to select multiple, non-contiguous elements of an array at the exact same time.
*   In Angular/TypeScript, if you want to extract multiple specific elements from an array, you have to run a map or filter, or search manually.
*   In NumPy, you can pass an array of integers as an index. This tells NumPy: "Give me the elements at these exact positions."
*   This is incredibly powerful because it replaces slow Python loops with pre-compiled C-speed operations.

### Simple Explanation with an Everyday Analogy
Imagine you are at a **grocery store** with a shopping cart. The grocery items are lined up on a single long shelf:
*   **Standard Slicing**: You walk down the shelf and grab everything from Item 2 to Item 5.
*   **Fancy Indexing**: You have a specific shopping list: "I need Item 1, Item 4, and Item 8." You do not walk through every single item. You target those three specific items and place them directly into your cart.



#### 1D Array Fancy Indexing
To use fancy indexing, you pass a list of indices inside the square brackets. This requires **double square brackets** `a[[index_list]]`.

In [2]:
import numpy as np

a = np.array([10, 22, 35, 41, 58, 63, 77, 89])

# We want elements at index 1, 3, and 6
indices = [1, 3, 6]
selected = a[indices]

print("Original array:", a)
print("Selected elements:", selected)

Original array: [10 22 35 41 58 63 77 89]
Selected elements: [22 41 77]


#### 2D Array Fancy Indexing: Selecting Specific Rows
You can also use fancy indexing on 2D arrays (matrices). If you pass a single list of indices to a 2D array, NumPy selects those specific rows.

In [3]:
import numpy as np

matrix = np.array([
    [10, 11, 12],
    [20, 21, 22],
    [30, 31, 32],
    [40, 41, 42]
])

# Let's select Row 0, Row 2, and Row 3
selected_rows = matrix[[0, 2, 3]]

print("Selected Rows:\n", selected_rows)

Selected Rows:
 [[10 11 12]
 [30 31 32]
 [40 41 42]]


#### 2D Array Fancy Indexing: Selecting Specific Coordinate Points
If you pass **two lists of indices** inside the brackets `matrix[[rows], [columns]]`, NumPy will pair them up like `(x, y)` coordinate points and extract single elements.


In [4]:
import numpy as np

matrix = np.array([
    [10, 11, 12],
    [20, 21, 22],
    [30, 31, 32],
    [40, 41, 42]
])

# We want to select:
# 1. Point at Row 0, Column 1 (Value: 11)
# 2. Point at Row 2, Column 2 (Value: 32)
# 3. Point at Row 3, Column 0 (Value: 40)
selected_points = matrix[[0, 2, 3], [1, 2, 0]]

print("Selected elements:", selected_points)

Selected elements: [11 32 40]


#### Fancy Indexing Creates a COPY, Not a View!
This is a critical memory detail. In Module 4, we learned that standard slicing returns a **view** (changing the slice changes the original array).
However, **fancy indexing always returns a copy** of the data.

In [5]:
import numpy as np

original = np.array([1, 2, 3, 4, 5])
fancy = original[[0, 2, 4]] # Elements [1, 3, 5]

print("Fancy before:", fancy)

# Let's change the first element of our fancy selection
fancy[0] = 99

print("Fancy after:", fancy)
print("Original after:", original) # The original array remains completely unchanged!

Fancy before: [1 3 5]
Fancy after: [99  3  5]
Original after: [1 2 3 4 5]


### Common Mistakes Beginners Make
1.  **Forgetting the double brackets**: Writing `a[1, 3]` on a 1D array thinking it means "get index 1 and 3". This causes an error because `a[1, 3]` is interpreted as a 2D coordinate lookup. Always use `a[[1, 3]]`.
2.  **Assuming fancy indexing is a view**: Expecting modifications to a fancy-indexed array to update the original data. If you want to modify specific indices in the original array, assign to them directly: `original[[0, 2, 4]] = 99`.


#### Exercise 1
Create a 1D array of even numbers from 2 to 20. Use fancy indexing to select the elements at indices `[1, 4, 7]`.

In [6]:
import numpy as np
a = np.arange(2, 21, 2) # [2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
result = a[[1, 4, 7]]
print("Array:", a)
print("Selected:", result)

Array: [ 2  4  6  8 10 12 14 16 18 20]
Selected: [ 4 10 16]


*Explanation*: `np.arange(2, 21, 2)` generates even numbers up to 20. Index `1` is `4`, index `4` is `10`, and index `7` is `16`. Passing them as a list inside brackets selects them.


#### Exercise 2
You are given a 2D matrix representing student IDs and their exam grades:
```python
grades = np.array([
    [101, 85],
    [102, 42],
    [103, 91],
    [104, 73]
])
```
Use fancy indexing to extract the rows for student IDs `101`, `103`, and `104` (indices `0`, `2`, and `3`).


In [7]:
import numpy as np
grades = np.array([
    [101, 85],
    [102, 42],
    [103, 91],
    [104, 73]
])
selected_students = grades[[0, 2, 3]]
print(selected_students)

[[101  85]
 [103  91]
 [104  73]]


*Explanation*: Passing a single list `[0, 2, 3]` to the 2D array selects the rows at those indices, returning a new 2D array.

#### Exercise 3
Given a 4x4 grid of numbers:
```python
grid = np.arange(1, 17).reshape(4, 4)
```
Extract the four corner elements of this grid (top-left, top-right, bottom-left, bottom-right) as a single 1D array using coordinate fancy indexing.


In [8]:
import numpy as np
grid = np.arange(1, 17).reshape(4, 4)
# Corners are:
# Top-Left: Row 0, Col 0 (1)
# Top-Right: Row 0, Col 3 (4)
# Bottom-Left: Row 3, Col 0 (13)
# Bottom-Right: Row 3, Col 3 (16)
corners = grid[[0, 0, 3, 3], [0, 3, 0, 3]]
print("Grid:\n", grid)
print("Corners:", corners)

Grid:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Corners: [ 1  4 13 16]


*Explanation*: We pair row indices `[0, 0, 3, 3]` with column indices `[0, 3, 0, 3]`. This selects elements at coordinate points `(0,0)`, `(0,3)`, `(3,0)`, and `(3,3)`.
