# Linear Algebra with NumPy

In data science, machine learning, and computer graphics, data is represented as matrices and vectors.
For example:
*   A user's preferences might be stored as a vector.
*   The connections in a neural network are stored as a 2D matrix.

To process this data, we need to perform **linear algebra** operations:
*   **Matrix Multiplication (Dot Product)**: Combines two matrices to calculate weight changes or transitions.
*   **Determinant**: A single number that represents how much a matrix scales space.
*   **Inverse**: The matrix equivalent of division. If you want to solve an equation $A \cdot x = B$, you need to find the inverse of $A$ (written as $A^-1$) so $x = A^-1 \cdot B$.

Writing these operations by hand in Python is extremely slow and requires complicated nested loops. NumPy's `linalg` module runs these complex math equations at C-speed, making them run in microseconds.

### Simple Explanation with an Everyday Analogy
Imagine you are running a **clothing shop** that sells t-shirts and hoodies.
*   **Prices Matrix**: T-shirts cost $10, Hoodies cost $20.
*   **Quantity Ordered Matrix**: Customer A orders 3 t-shirts and 1 hoodie. Customer B orders 2 t-shirts and 4 hoodies.

**Matrix Multiplication** is the single operation that multiplies the prices by the quantities and adds them together for every customer at once. It automatically gives you a final receipt: Customer A owes $50, and Customer B owes $100.


#### True Matrix Multiplication using the `@` Operator
In Module 5, we saw that using `*` multiplies arrays elementwise. In linear algebra, matrix multiplication is a completely different process.
We use the `@` operator or `np.matmul()` for true matrix multiplication.

In [1]:
import numpy as np

# Matrix A (2x2)
A = np.array([
    [1, 2],
    [3, 4]
])

# Matrix B (2x2)
B = np.array([
    [5, 6],
    [7, 8]
])

# Elementwise multiplication (WRONG for linear algebra)
print("Elementwise (A * B):\n", A * B)

# Matrix Multiplication (CORRECT)
print("Matrix Multiplication (A @ B):\n", A @ B)

Elementwise (A * B):
 [[ 5 12]
 [21 32]]
Matrix Multiplication (A @ B):
 [[19 22]
 [43 50]]


#### Finding the Determinant and Inverse of a Matrix
We use the `np.linalg` module to find a matrix's determinant and inverse.


In [2]:
import numpy as np

A = np.array([
    [1, 2],
    [3, 4]
])

# Calculate Determinant
det = np.linalg.det(A)
print("Determinant of A:", det)

# Calculate Matrix Inverse (A^-1)
inv = np.linalg.inv(A)
print("Inverse of A:\n", inv)

Determinant of A: -2.0000000000000004
Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]


### Common Mistakes Beginners Make
1.  **Using `*` instead of `@`**: This is the most common mistake. `A * B` multiplies matching positions. It does not perform mathematical matrix multiplication. Always use `A @ B`.
2.  **Multiplying Incompatible Shapes**: To multiply two matrices, the number of columns in Matrix A **must equal** the number of rows in Matrix B. If they don't match, NumPy will throw a `ValueError`.
3.  **Inverting a Singular Matrix**: Some matrices have a determinant of `0`. These are called singular matrices (or degenerate matrices) and cannot be inverted. Trying to invert them will throw a `LinAlgError`.

#### Exercise 1
Create a 2x3 matrix filled with ones and a 3x2 matrix filled with the number `3`. Multiply them using the `@` operator and print the resulting matrix and its shape.

In [3]:
import numpy as np
m1 = np.ones((2, 3))
m2 = np.full((3, 2), 3)
result = m1 @ m2
print("Result:\n", result)
print("Shape:", result.shape)

Result:
 [[9. 9.]
 [9. 9.]]
Shape: (2, 2)


*Explanation*: Multiplying a (2x3) matrix by a (3x2) matrix is valid because the inner dimensions (3) match. The resulting matrix has the outer dimensions (2x2).


#### Exercise 2
Given this matrix:
```python
M = np.array([
    [3, 8],
    [4, 6]
])
```
1. Calculate its determinant.
2. Calculate its inverse matrix.

In [4]:
import numpy as np
M = np.array([
    [3, 8],
    [4, 6]
])
det = np.linalg.det(M)
inv = np.linalg.inv(M)
print("Determinant:", np.round(det, decimals=2))
print("Inverse:\n", inv)

Determinant: -14.0
Inverse:
 [[-0.42857143  0.57142857]
 [ 0.28571429 -0.21428571]]


*Explanation*: The determinant is $(3 	imes 6) - (8 	imes 4) = 18 - 32 = -14$. Since the determinant is not zero, the inverse is safely calculated.


#### Exercise 3
Verify the mathematical rule: $A \cdot A^-1 = I$ (where $I$ is the Identity Matrix `[[1, 0], [0, 1]]`).
Create matrix $A = [[2, 5], [1, 3]]$, calculate its inverse, multiply them together using the `@` operator, and print the result. Use `np.round()` to clean up minor floating-point rendering decimals.



In [5]:
import numpy as np
A = np.array([
    [2, 5],
    [1, 3]
])
inv_A = np.linalg.inv(A)
identity = A @ inv_A
print("Identity (unrounded):\n", identity)
print("Identity (rounded):\n", np.round(identity))

Identity (unrounded):
 [[1. 0.]
 [0. 1.]]
Identity (rounded):
 [[1. 0.]
 [0. 1.]]


*Explanation*: Multiplying a matrix by its inverse yields the Identity Matrix. Due to computer floating-point approximations, a tiny error (`4.44e-16`) might appear. Rounding cleans this up into clean `1.0` and `0.0` values.
