# Indexing and Slicing (Getting Data from Arrays)

Imagine a **multi-story bookshelf**:
*   **Index**: To get one specific book, you say: "Get the book on Shelf 1, Position 3."
*   **Slicing**: To get a group of books, you say: "Get all books on Shelf 1, from Position 2 to Position 4."
*   **Rows and Columns**: The bookshelf has rows (shelves) and columns (vertical slots). You can ask for a whole shelf (a row) or all books in the third slot across all shelves (a column).


## Code Examples

#### A) 1D Slicing: `[start:stop:step]`
The slicing syntax is `[start:stop:step]`.
*   **start**: The index where we begin (inclusive). Defaults to `0`.
*   **stop**: The index where we end (**exclusive** - it does not include this index). Defaults to the end of the array.
*   **step**: How many steps to skip. Defaults to `1`.

In [1]:
import numpy as np

a = np.array([10, 20, 30, 40, 50, 60])

print("Original array:", a)
print("First element (index 0):", a[0])
print("Last element (index -1):", a[-1])
print("Slice [1:4] (indices 1, 2, 3):", a[1:4])
print("Slice [::2] (every second element):", a[::2])
print("Reverse array [::-1]:", a[::-1])

Original array: [10 20 30 40 50 60]
First element (index 0): 10
Last element (index -1): 60
Slice [1:4] (indices 1, 2, 3): [20 30 40]
Slice [::2] (every second element): [10 30 50]
Reverse array [::-1]: [60 50 40 30 20 10]


#### B) 2D Indexing: Chain Indexing vs. Multi-dimensional Indexing
In TypeScript, if you have a nested array (a matrix), you access elements using two sets of brackets: `matrix[row][col]`. This is called **chain indexing**.
In NumPy, you can do that too, but you should **prefer multi-dimensional indexing** using a single set of brackets and a comma: `matrix[row, col]`.

*Why is `matrix[row, col]` better?*
1. **It is faster**: NumPy looks up the value directly in contiguous memory.
2. **It uses less memory**: Chain indexing `matrix[row][col]` first extracts the entire `row` as a temporary array, then looks up the `col` in that new array. This wastes CPU cycles.

In [2]:
import numpy as np

matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

# Multi-dimensional indexing (Row 1, Column 2)
# Remember: Indices start at 0!
print("Value at row 1, col 2:", matrix[1, 2])

Value at row 1, col 2: 7


#### C) 2D Slicing: Extracting Rows, Columns, and Quadrants
You can use the colon `:` in 2D arrays to select entire rows or columns.
*   `:` by itself means "select all".
*   `matrix[1, :]` means "Row 1, all columns".
*   `matrix[:, 2]` means "all rows, Column 2".
*   `matrix[0:2, 1:3]` means "Rows 0 to 1, Columns 1 to 2" (a quadrant/submatrix).


In [3]:
import numpy as np

matrix = np.array([
    [1,  2,  3,  4],
    [5,  6,  7,  8],
    [9, 10, 11, 12]
])

print("Entire Row 1:\n", matrix[1, :])
print("Entire Column 2:\n", matrix[:, 2])
print("Quadrant (Rows 0-1, Columns 1-2):\n", matrix[0:2, 1:3])

Entire Row 1:
 [5 6 7 8]
Entire Column 2:
 [ 3  7 11]
Quadrant (Rows 0-1, Columns 1-2):
 [[2 3]
 [6 7]]



#### D) Slicing creates a "View", NOT a "Copy"
This is the most important memory concept in NumPy. Let's see what happens if we slice an array and change a value in that slice.


In [4]:
import numpy as np

original = np.array([1, 2, 3, 4, 5])
my_slice = original[1:4] # Elements [2, 3, 4]

print("Original before:", original)
print("Slice before:", my_slice)

# Let's modify the first element of our slice
my_slice[0] = 99

print("Slice after:", my_slice)
print("Original after:", original) # Notice how the original array also changed!

Original before: [1 2 3 4 5]
Slice before: [2 3 4]
Slice after: [99  3  4]
Original after: [ 1 99  3  4  5]


*How to avoid this?*
If you want an independent copy that does not affect the original array, use the `.copy()` method:
`my_copy = original[1:4].copy()`


### Common Mistakes Beginners Make
1.  **Forgetting that stop indices are exclusive**: Writing `a[1:3]` thinking it will get elements at indices 1, 2, and 3. It only gets 1 and 2!
2.  **Using `matrix[row][col]` out of habit**: While it works, it is slower. Always use `matrix[row, col]`.
3.  **Accidentally changing original data**: Forgetting that slices are "views". If you modify a slice, you modify the original array. Use `.copy()` if you want a separate copy.


#### Exercise 1
Create a 1D array of numbers from 10 to 20. Extract the elements at index 3, 5, and the last element.

In [5]:
import numpy as np
a = np.arange(10, 21) # [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
print("Index 3:", a[3])
print("Index 5:", a[5])
print("Last:", a[-1])

Index 3: 13
Index 5: 15
Last: 20


*Explanation*: `np.arange(10, 21)` generates numbers from 10 up to (but not including) 21. Standard negative index `-1` safely grabs the last element.


#### Exercise 2
Given this 2D array:

In [ ]:
grid = np.array([
    [10, 11, 12, 13],
    [14, 15, 16, 17],
    [18, 19, 20, 21]
])

1. Slice the second row.
2. Slice the third column.
3. Slice the middle 2x2 quadrant (numbers `15, 16` and `19, 20`).

In [6]:
import numpy as np
grid = np.array([
    [10, 11, 12, 13],
    [14, 15, 16, 17],
    [18, 19, 20, 21]
])

# 1. Second row (index 1)
row_1 = grid[1, :]
# 2. Third column (index 2)
col_2 = grid[:, 2]
# 3. Middle 2x2 quadrant
quad = grid[1:3, 1:3]

print("Row 1:", row_1)
print("Col 2:", col_2)
print("Quadrant:\n", quad)

Row 1: [14 15 16 17]
Col 2: [12 16 20]
Quadrant:
 [[15 16]
 [19 20]]


*Explanation*:
*   `grid[1, :]` selects the second row (index 1) and all columns.
*   `grid[:, 2]` selects all rows, but only the third column (index 2).
*   `grid[1:3, 1:3]` selects row indices 1 and 2 (3 is exclusive), and column indices 1 and 2 (3 is exclusive).

#### Exercise 3 (Hard)
Given a 4x4 matrix of numbers from 1 to 16:

In [ ]:
matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

Reverse the order of the columns (make the first column last, the last column first), but keep the rows in their original top-to-bottom order. Do this using slicing.


In [7]:
import numpy as np
matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

# We select all rows (:), but reverse the columns (::-1)
reversed_cols = matrix[:, ::-1]
print(reversed_cols)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


*Explanation*: In the column selection position (the second index), we write `::-1`. This means: "start from the end, go to the beginning, with step -1" (which reverses the order). Since we used `:` in the row position, rows are unaffected.
