# Broadcasting (The Magic of Stretching Arrays)

What happens if we want to add a single row `[10, 20, 30]` to a matrix with 3 rows and 3 columns?
In regular programming, this would throw an error because the shapes are different. You would have to write a loop to add the row to each row of the matrix manually.

NumPy solves this with **Broadcasting**. Broadcasting is a set of rules that allows NumPy to perform math operations on arrays of **different shapes**.
*   NumPy **virtually stretches** the smaller array to match the shape of the larger array.
*   "Virtually" means NumPy does **not** actually duplicate the data in memory (which would waste RAM). It does this math efficiently in C-level loops.


### Simple Explanation with an Everyday Analogy

Imagine you have a rubber stamp that has one row of ink: `[A, B, C]`.
You have a grid on a paper with 3 empty rows.
Instead of writing "A, B, C" on each row one by one, you take your rubber stamp and slide it downwards. It leaves the pattern `[A, B, C]` on all 3 rows instantly.
That stamp is the smaller array, and the grid is the larger array. You "stretched" your single-row stamp across multiple rows!

### Rules of Compatibility
NumPy cannot broadcast any two arrays. They must be **compatible**. To check if two arrays are compatible, NumPy compares their shapes **from right to left** (last dimension to first).

Two dimensions are compatible if:
1.  They are **exactly equal** in size, OR
2.  One of them is **exactly 1**.

If neither condition is met, NumPy will throw a `ValueError` (operands could not be broadcast together).

Let's look at an example:
*   Array 1 Shape: `(4, 3)`
*   Array 2 Shape: `(1, 3)`

Let's compare them from right to left:
*   **Last dimension**: Array 1 is `3`, Array 2 is `3`. They are **equal**! (Compatible ✅)
*   **First dimension**: Array 1 is `4`, Array 2 is `1`. One of them is `1`! (Compatible ✅)

Since both dimensions are compatible, NumPy can broadcast them! The final shape of the output will be the maximum of the two: `(4, 3)`.


#### Adding a 1D Array to a 2D Array
Let's add a 1D array of shape `(3,)` to a 2D array of shape `(2, 3)`.

In [1]:
import numpy as np

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
]) # Shape: (2, 3)

row = np.array([10, 20, 30]) # Shape: (3,)

# NumPy virtually stretches row to be:
# [[10, 20, 30],
#  [10, 20, 30]]
# Then adds them elementwise!
result = matrix + row
print("Result of matrix + row:\n", result)

Result of matrix + row:
 [[11 22 33]
 [14 25 36]]


#### Column Vector and Row Vector Broadcasting (Creating a Grid)

Let's do something amazing. Let's broadcast a **column vector** of shape `(3, 1)` with a **row vector** of shape `(1, 3)`.
*   NumPy stretches the column vector `(3, 1)` horizontally to become `(3, 3)`.
*   NumPy stretches the row vector `(1, 3)` vertically to become `(3, 3)`.
*   Then it multiplies them to make a perfect grid (multiplication table)!

In [2]:
import numpy as np

col_vector = np.array([[1], [2], [3]]) # Shape: (3, 1)
row_vector = np.array([[10, 20, 30]]) # Shape: (1, 3)

# Multiplication table using broadcasting!
grid = col_vector * row_vector
print("Generated Grid:\n", grid)

Generated Grid:
 [[10 20 30]
 [20 40 60]
 [30 60 90]]


#### Incompatible Shapes (The Error)
Let's see what happens if we try to broadcast incompatible shapes.
*   Array 1 Shape: `(2, 3)`
*   Array 2 Shape: `(2, 2)`

Compare from right to left:
*   Last dimension: `3` vs `2`. They are not equal, and neither is 1!
This immediately fails.

In [3]:
import numpy as np

a = np.ones((2, 3))
b = np.ones((2, 2))

try:
    result = a + b
except ValueError as e:
    print("Error caught:", e)

Error caught: operands could not be broadcast together with shapes (2,3) (2,2) 



### Common Mistakes Beginners Make
1.  **Forgetting right-to-left alignment**: Beginners often think shapes `(3, 4)` and `(3,)` can broadcast because "they both have 3".
    *   Let's check: NumPy aligns them as `(3, 4)` and `( , 3)`.
    *   The last dimensions are `4` and `3`. They are not equal and neither is 1. They are **not compatible**!
    *   To fix this, you must reshape the second array to `(3, 1)` so it aligns as `(3, 4)` and `(3, 1)`.
2.  **Assuming broadcasting copies data**: Broadcasting does not create physical copies of data. It is highly optimized and memory-efficient.



#### Exercise
Are these array shapes compatible for broadcasting? If yes, what will be the shape of the final result?
1.  `(5, 1)` and `(1, 4)`
2.  `(3, 3)` and `(3, 2)`
3.  `(8, 1, 6)` and `(1, 5, 1)`

1.  **`(5, 1)` and `(1, 4)`**: **Compatible** ✅
    *   Right-to-left check: `1` vs `4` (one is 1 ✅), `5` vs `1` (one is 1 ✅).
    *   Final shape: `(5, 4)`.
2.  **`(3, 3)` and `(3, 2)`**: **Incompatible** ❌
    *   Right-to-left check: `3` vs `2` (not equal, and neither is 1 ❌).
3.  **`(8, 1, 6)` and `(1, 5, 1)`**: **Compatible** ✅
    *   Right-to-left check: `6` vs `1` (one is 1 ✅), `1` vs `5` (one is 1 ✅), `8` vs `1` (one is 1 ✅).
    *   Final shape: `(8, 5, 6)`.

#### Exercise
Create a 3x3 matrix containing all zeros. Create a 1D array `[100, 200, 300]`. Add them together using broadcasting so that the output looks like this:
```text
[[100. 200. 300.]
 [100. 200. 300.]
 [100. 200. 300.]]
```

In [4]:
import numpy as np

zeros_grid = np.zeros((3, 3))
row_to_add = np.array([100, 200, 300])

result = zeros_grid + row_to_add
print(result)

[[100. 200. 300.]
 [100. 200. 300.]
 [100. 200. 300.]]


*Explanation*: The zeros grid has shape `(3, 3)`. The row array has shape `(3,)` which matches the trailing dimension of the grid. NumPy broadcasts the row vertically 3 times, adding `[100, 200, 300]` to each of the three rows of zeros.


#### Exercise 3
Using broadcasting, generate a 12x12 addition grid for numbers 1 to 12.
*(Hint: Create a 1D column array from 1 to 12 of shape `(12, 1)`, and a 1D row array from 1 to 12 of shape `(1, 12)`, then add them together).*


In [5]:
import numpy as np

# Create numbers from 1 to 12
numbers = np.arange(1, 13) # [1, 2, ..., 12]

# Reshape to make a column vector of shape (12, 1)
col = numbers.reshape(12, 1)

# Reshape to make a row vector of shape (1, 12)
row = numbers.reshape(1, 12)

# Add them using broadcasting
addition_grid = col + row

print("Shape of col:", col.shape)
print("Shape of row:", row.shape)
print("Shape of result:", addition_grid.shape)
print("First 3 rows of the grid:\n", addition_grid[:3, :])

Shape of col: (12, 1)
Shape of row: (1, 12)
Shape of result: (12, 12)
First 3 rows of the grid:
 [[ 2  3  4  5  6  7  8  9 10 11 12 13]
 [ 3  4  5  6  7  8  9 10 11 12 13 14]
 [ 4  5  6  7  8  9 10 11 12 13 14 15]]


*Explanation*:
*   `col` has shape `(12, 1)` and `row` has shape `(1, 12)`.
*   During broadcasting, `col` is stretched horizontally to size `(12, 12)`, and `row` is stretched vertically to size `(12, 12)`.
*   The final grid contains the addition of every column value with every row value (e.g., cell `[0, 0]` is `1 + 1 = 2`, cell `[0, 1]` is `1 + 2 = 3`, etc.).
